/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
export * as computeCluster from './compute-cluster';
export * as computeClusterHostGroup from './compute-cluster-host-group';
export * as computeClusterVmAffinityRule from './compute-cluster-vm-affinity-rule';
export * as computeClusterVmAntiAffinityRule from './compute-cluster-vm-anti-affinity-rule';
export * as computeClusterVmDependencyRule from './compute-cluster-vm-dependency-rule';
export * as computeClusterVmGroup from './compute-cluster-vm-group';
export * as computeClusterVmHostRule from './compute-cluster-vm-host-rule';
export * as contentLibrary from './content-library';
export * as contentLibraryItem from './content-library-item';
export * as customAttribute from './custom-attribute';
export * as datacenter from './datacenter';
export * as datastoreCluster from './datastore-cluster';
export * as datastoreClusterVmAntiAffinityRule from './datastore-cluster-vm-anti-affinity-rule';
export * as distributedPortGroup from './distributed-port-group';
export * as distributedVirtualSwitch from './distributed-virtual-switch';
export * as dpmHostOverride from './dpm-host-override';
export * as drsVmOverride from './drs-vm-override';
export * as entityPermissions from './entity-permissions';
export * as file from './file';
export * as folder from './folder';
export * as guestOsCustomization from './guest-os-customization';
export * as haVmOverride from './ha-vm-override';
export * as host from './host';
export * as hostPortGroup from './host-port-group';
export * as hostVirtualSwitch from './host-virtual-switch';
export * as licenseResource from './license-resource';
export * as nasDatastore from './nas-datastore';
export * as resourcePool from './resource-pool';
export * as role from './role';
export * as storageDrsVmOverride from './storage-drs-vm-override';
export * as tag from './tag';
export * as tagCategory from './tag-category';
export * as vappContainer from './vapp-container';
export * as vappEntity from './vapp-entity';
export * as virtualDisk from './virtual-disk';
export * as virtualMachine from './virtual-machine';
export * as virtualMachineSnapshot from './virtual-machine-snapshot';
export * as vmStoragePolicy from './vm-storage-policy';
export * as vmfsDatastore from './vmfs-datastore';
export * as vnic from './vnic';
export * as dataVsphereComputeCluster from './data-vsphere-compute-cluster';
export * as dataVsphereComputeClusterHostGroup from './data-vsphere-compute-cluster-host-group';
export * as dataVsphereContentLibrary from './data-vsphere-content-library';
export * as dataVsphereContentLibraryItem from './data-vsphere-content-library-item';
export * as dataVsphereCustomAttribute from './data-vsphere-custom-attribute';
export * as dataVsphereDatacenter from './data-vsphere-datacenter';
export * as dataVsphereDatastore from './data-vsphere-datastore';
export * as dataVsphereDatastoreCluster from './data-vsphere-datastore-cluster';
export * as dataVsphereDatastoreStats from './data-vsphere-datastore-stats';
export * as dataVsphereDistributedVirtualSwitch from './data-vsphere-distributed-virtual-switch';
export * as dataVsphereDynamic from './data-vsphere-dynamic';
export * as dataVsphereFolder from './data-vsphere-folder';
export * as dataVsphereGuestOsCustomization from './data-vsphere-guest-os-customization';
export * as dataVsphereHost from './data-vsphere-host';
export * as dataVsphereHostPciDevice from './data-vsphere-host-pci-device';
export * as dataVsphereHostThumbprint from './data-vsphere-host-thumbprint';
export * as dataVsphereHostVgpuProfile from './data-vsphere-host-vgpu-profile';
export * as dataVsphereLicense from './data-vsphere-license';
export * as dataVsphereNetwork from './data-vsphere-network';
export * as dataVsphereOvfVmTemplate from './data-vsphere-ovf-vm-template';
export * as dataVsphereResourcePool from './data-vsphere-resource-pool';
export * as dataVsphereRole from './data-vsphere-role';
export * as dataVsphereStoragePolicy from './data-vsphere-storage-policy';
export * as dataVsphereTag from './data-vsphere-tag';
export * as dataVsphereTagCategory from './data-vsphere-tag-category';
export * as dataVsphereVappContainer from './data-vsphere-vapp-container';
export * as dataVsphereVirtualMachine from './data-vsphere-virtual-machine';
export * as dataVsphereVmfsDisks from './data-vsphere-vmfs-disks';
export * as provider from './provider';

