/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'computeCluster', { get: function () { return require('./compute-cluster'); } });
Object.defineProperty(exports, 'computeClusterHostGroup', { get: function () { return require('./compute-cluster-host-group'); } });
Object.defineProperty(exports, 'computeClusterVmAffinityRule', { get: function () { return require('./compute-cluster-vm-affinity-rule'); } });
Object.defineProperty(exports, 'computeClusterVmAntiAffinityRule', { get: function () { return require('./compute-cluster-vm-anti-affinity-rule'); } });
Object.defineProperty(exports, 'computeClusterVmDependencyRule', { get: function () { return require('./compute-cluster-vm-dependency-rule'); } });
Object.defineProperty(exports, 'computeClusterVmGroup', { get: function () { return require('./compute-cluster-vm-group'); } });
Object.defineProperty(exports, 'computeClusterVmHostRule', { get: function () { return require('./compute-cluster-vm-host-rule'); } });
Object.defineProperty(exports, 'contentLibrary', { get: function () { return require('./content-library'); } });
Object.defineProperty(exports, 'contentLibraryItem', { get: function () { return require('./content-library-item'); } });
Object.defineProperty(exports, 'customAttribute', { get: function () { return require('./custom-attribute'); } });
Object.defineProperty(exports, 'datacenter', { get: function () { return require('./datacenter'); } });
Object.defineProperty(exports, 'datastoreCluster', { get: function () { return require('./datastore-cluster'); } });
Object.defineProperty(exports, 'datastoreClusterVmAntiAffinityRule', { get: function () { return require('./datastore-cluster-vm-anti-affinity-rule'); } });
Object.defineProperty(exports, 'distributedPortGroup', { get: function () { return require('./distributed-port-group'); } });
Object.defineProperty(exports, 'distributedVirtualSwitch', { get: function () { return require('./distributed-virtual-switch'); } });
Object.defineProperty(exports, 'dpmHostOverride', { get: function () { return require('./dpm-host-override'); } });
Object.defineProperty(exports, 'drsVmOverride', { get: function () { return require('./drs-vm-override'); } });
Object.defineProperty(exports, 'entityPermissions', { get: function () { return require('./entity-permissions'); } });
Object.defineProperty(exports, 'file', { get: function () { return require('./file'); } });
Object.defineProperty(exports, 'folder', { get: function () { return require('./folder'); } });
Object.defineProperty(exports, 'guestOsCustomization', { get: function () { return require('./guest-os-customization'); } });
Object.defineProperty(exports, 'haVmOverride', { get: function () { return require('./ha-vm-override'); } });
Object.defineProperty(exports, 'host', { get: function () { return require('./host'); } });
Object.defineProperty(exports, 'hostPortGroup', { get: function () { return require('./host-port-group'); } });
Object.defineProperty(exports, 'hostVirtualSwitch', { get: function () { return require('./host-virtual-switch'); } });
Object.defineProperty(exports, 'licenseResource', { get: function () { return require('./license-resource'); } });
Object.defineProperty(exports, 'nasDatastore', { get: function () { return require('./nas-datastore'); } });
Object.defineProperty(exports, 'resourcePool', { get: function () { return require('./resource-pool'); } });
Object.defineProperty(exports, 'role', { get: function () { return require('./role'); } });
Object.defineProperty(exports, 'storageDrsVmOverride', { get: function () { return require('./storage-drs-vm-override'); } });
Object.defineProperty(exports, 'tag', { get: function () { return require('./tag'); } });
Object.defineProperty(exports, 'tagCategory', { get: function () { return require('./tag-category'); } });
Object.defineProperty(exports, 'vappContainer', { get: function () { return require('./vapp-container'); } });
Object.defineProperty(exports, 'vappEntity', { get: function () { return require('./vapp-entity'); } });
Object.defineProperty(exports, 'virtualDisk', { get: function () { return require('./virtual-disk'); } });
Object.defineProperty(exports, 'virtualMachine', { get: function () { return require('./virtual-machine'); } });
Object.defineProperty(exports, 'virtualMachineSnapshot', { get: function () { return require('./virtual-machine-snapshot'); } });
Object.defineProperty(exports, 'vmStoragePolicy', { get: function () { return require('./vm-storage-policy'); } });
Object.defineProperty(exports, 'vmfsDatastore', { get: function () { return require('./vmfs-datastore'); } });
Object.defineProperty(exports, 'vnic', { get: function () { return require('./vnic'); } });
Object.defineProperty(exports, 'dataVsphereComputeCluster', { get: function () { return require('./data-vsphere-compute-cluster'); } });
Object.defineProperty(exports, 'dataVsphereComputeClusterHostGroup', { get: function () { return require('./data-vsphere-compute-cluster-host-group'); } });
Object.defineProperty(exports, 'dataVsphereContentLibrary', { get: function () { return require('./data-vsphere-content-library'); } });
Object.defineProperty(exports, 'dataVsphereContentLibraryItem', { get: function () { return require('./data-vsphere-content-library-item'); } });
Object.defineProperty(exports, 'dataVsphereCustomAttribute', { get: function () { return require('./data-vsphere-custom-attribute'); } });
Object.defineProperty(exports, 'dataVsphereDatacenter', { get: function () { return require('./data-vsphere-datacenter'); } });
Object.defineProperty(exports, 'dataVsphereDatastore', { get: function () { return require('./data-vsphere-datastore'); } });
Object.defineProperty(exports, 'dataVsphereDatastoreCluster', { get: function () { return require('./data-vsphere-datastore-cluster'); } });
Object.defineProperty(exports, 'dataVsphereDistributedVirtualSwitch', { get: function () { return require('./data-vsphere-distributed-virtual-switch'); } });
Object.defineProperty(exports, 'dataVsphereDynamic', { get: function () { return require('./data-vsphere-dynamic'); } });
Object.defineProperty(exports, 'dataVsphereFolder', { get: function () { return require('./data-vsphere-folder'); } });
Object.defineProperty(exports, 'dataVsphereGuestOsCustomization', { get: function () { return require('./data-vsphere-guest-os-customization'); } });
Object.defineProperty(exports, 'dataVsphereHost', { get: function () { return require('./data-vsphere-host'); } });
Object.defineProperty(exports, 'dataVsphereHostPciDevice', { get: function () { return require('./data-vsphere-host-pci-device'); } });
Object.defineProperty(exports, 'dataVsphereHostThumbprint', { get: function () { return require('./data-vsphere-host-thumbprint'); } });
Object.defineProperty(exports, 'dataVsphereLicense', { get: function () { return require('./data-vsphere-license'); } });
Object.defineProperty(exports, 'dataVsphereNetwork', { get: function () { return require('./data-vsphere-network'); } });
Object.defineProperty(exports, 'dataVsphereOvfVmTemplate', { get: function () { return require('./data-vsphere-ovf-vm-template'); } });
Object.defineProperty(exports, 'dataVsphereResourcePool', { get: function () { return require('./data-vsphere-resource-pool'); } });
Object.defineProperty(exports, 'dataVsphereRole', { get: function () { return require('./data-vsphere-role'); } });
Object.defineProperty(exports, 'dataVsphereStoragePolicy', { get: function () { return require('./data-vsphere-storage-policy'); } });
Object.defineProperty(exports, 'dataVsphereTag', { get: function () { return require('./data-vsphere-tag'); } });
Object.defineProperty(exports, 'dataVsphereTagCategory', { get: function () { return require('./data-vsphere-tag-category'); } });
Object.defineProperty(exports, 'dataVsphereVappContainer', { get: function () { return require('./data-vsphere-vapp-container'); } });
Object.defineProperty(exports, 'dataVsphereVirtualMachine', { get: function () { return require('./data-vsphere-virtual-machine'); } });
Object.defineProperty(exports, 'dataVsphereVmfsDisks', { get: function () { return require('./data-vsphere-vmfs-disks'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

